AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-eventbridge-pipes-demo

  SAM Template for aws-eventbridge-pipes-demo

Resources:
  OrdersQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "orders-to-be-processed"
      RedrivePolicy:
        maxReceiveCount: 1
        deadLetterTargetArn: !GetAtt "OrdersDeadLetterQueue.Arn"

  OrdersDeadLetterQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "orders-to-be-processed-dlq"